name: 🚀 Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Create key.json from GitHub Secret
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $GITHUB_WORKSPACE/key.json

    - name: Deploy to Firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/key.json
      run: firebase deploy --project=sampleaaaa-firebase-ai-app
