name: 🚀 Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create service account JSON
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > key.json

      - name: Deploy with service account
        run: GOOGLE_APPLICATION_CREDENTIALS=key.json firebase deploy --project=sampleaaaa-firebase-ai-app
